# Generated by Django 5.0.9 on 2024-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='capture_light',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='update_available',
            field=models.BooleanField(default=False),
        ),
    ]
